### ISSUE TITLE
Suggestion: config option to block creation of new pins on interactive map

### ISSUE THREAD

**Issue by ZenDragonX** [shudnal/AutoPinSigns#2]
In an immersive experience it would be nice to block players from creating pins on the interactive map and only allow pins to be created by crafting signs otherwise the player just bypasses the signs to create pins and uses pins for everything.

A config option to block the creation of new pins on the interactive map would be nice.

NOTE:

Players should still be able to remove pins from the interactive map though in order to cleanup any stray pins.

Also they should be able to cross off pins on the interactive map as usual.

Just no creation of new pins.

Bonus: Limit the number of pins they can create manually to a config value.  But if that's too difficult then just blocking their creation entirely would be helpful. :)

**Comment by shudnal** [comment]
Nice feature. Check 1.1.7.
There is no way to distinct pins added by map clicking and other ones. So only complete prevention of new pins is an option.

**Comment by shudnal** [comment]
Damn it's the wrong mod. Still I think that feature is better fits NomapPrinter as it alters the map.
That mod is single-purpose straightforward one.

**Comment by ZenDragonX** [comment]
Great!  I saw the change.  Sure it makes sense on NomapPrinter.  Thank you!
